config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users', to: 'welcome#index'

  resources :articles
  resources :cars
  
  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/car.rb
class Car < ApplicationRecord
    validates :title, :avatar, :presence => true
    has_attached_file :avatar, styles: { medium: "400x400>", thumb: "100x100>" }, default_url: "/images/not_av_m.png"
    validates_attachment_content_type :avatar, content_type: ["image/jpeg", "image/gif", "image/png"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, 
       :rememberable, :validatable

  enum roles: [:user, :admin]

  def self.role_by_id id
    role = roles.key(id)
    role ? role.humanize : 'Not defined'
  end

  def self.roles_for_select
    # puts roles.keys.map{ |x| [x.humanize, x] }
    roles.values.map{ |x| [roles.key(x).humanize, x] }
  end

  protected
  def confirmation_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :username, :password, :role)}

        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :username, :password, :current_password, :role)}
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
      end
     
    def new
    end
    
    def create
        @article = Article.new(article_params)
       
        @article.save
        redirect_to @article
    end
       
      private
    def article_params
          params.require(:article).permit(:title, :text)
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    def index
        @cars = Car.all
    end
    
    def show
      @car = Car.find(params[:id])
      end
     
    def new
      if current_user.role != 1
        redirect_to('/cars')
      end
    end
    
    def create
      if current_user.role != 1
        redirect_to('/cars')
      end

      @car = Car.new(car_params)
      @car.created_by = current_user.username
      @car.save
        redirect_to @car
    end
       
      private
    def car_params
          params.require(:car).permit(:title, :description, :avatar)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>
<p><a href="/articles/new">Create a new article</a>
</p>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
   
    <p>
      <%= form.label :text %><br>
      <%= form.text_area :text %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/articles/show.html.erb
<p>
<strong>Title:</strong>
<%= @article.title %>
</p>

<p>
<strong>Text:</strong>
<%= @article.text %>
</p>
<p><a href="/articles/new">Create a new article</a> <a href="/articles">View all articles</a>
</p>

app/views/cars/index.html.erb
<h1>List of Cars</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Creation Date</th>
    <th>Created By</th>
    <th></th>
  </tr>
 
  <% @cars.each do |car| %>
    <tr>
      <td><%= car.title %></td>
      <td><%= car.created_at.strftime("%d/%m/%Y at %H:%M") %></td>
      <td><%= car.created_by %></td>
      <td><%= link_to 'Show', car_path(car) %></td>
    </tr>
  <% end %>
</table>

<p><% if current_user.role == 1 %> 
<a href="/cars/new">Create new car</a></td>
<% end %></p>

app/views/cars/new.html.erb
<h1>Create a new car</h1>
<%= form_with scope: :car, url: cars_path, local: true do |form| %>
    <p>
      <%= form.label :title %> (required)<br>
      <%= form.text_field :title, required: true %>
      </p>
   
    <p>
      <%= form.label :description %> (optional)<br>
      <%= form.text_area :description %>
    </p>

    <p class="field">
    <%= form.label :photo %><br />
    <%= form.file_field :avatar, as: :file %>
  </p> 

    <p>
      <%= form.submit %> <%= link_to 'Back to car list', cars_path %>
    </p>
  <% end %>

app/views/cars/show.html.erb
<h1> Car Details: </h1>

<table>
  <tr>
    <th>Title</th>
    <% if @car.description.present? %>
      <th>Description</th>
    <% end %>
    <th>Created By</th>
    <th>Photo</th>
  </tr>
 
    <tr>
      <td><%= @car.title %></td>
      <% if @car.description.present?  %>
        <td><%= @car.description %></td>
      <% end %>
      <td><%= @car.created_by %></td>
      <td><%= image_tag @car.avatar.url(:medium) %></td>
    </tr>
</table>

<p><a href="/cars">View car list</a>
<% if current_user.role == 1 %> 
  <a href="/cars/new">Create new car</a></td>
<% end %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Itay's Ruby Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.username %></strong> (<%= User.role_by_id(current_user.role) %>) 
  
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
<%= yield %>
      
      <p><a href="/articles">Go to articles</a>
<a href="/cars">Go to cars</a>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
This is the awesome blog that displays cars for some reason
</p>